### ISSUE TITLE
Take care of membrane_rtp_aac_plugin

### ISSUE THREAD

**Issue by varsill** [membraneframework/membrane_core#682]
A while ago the Membrane RTP AAC plugin was moved to the membrane-labs organization (https://github.com/membraneframework-labs/membrane_rtp_aac_plugin) because it contains only a depayloader (and no corresponding payloader) as well as the overall quality of the plugin requires some improvements. 
That plugin has been released on the hex.pm and is used for instance in membrane_demo/rtp_to_hls (and can be potentially used in more places), so it might be worth updating it.
Things to be done:
* refactor the code
* add AAC RTP payloader
* add tests

**Comment by kidq330** [comment]
Development plans:
1. RFC3640 (currently supported) specifies payloading of AAC with encapsulation :none, RFC6416 specifies no-op payloading of LATM(LOAS) encapsulated AAC, and should be more strictly separated as a streaming option. The focus of this task shifts to, and should end on, implementing the no-op payloader and depayloader for RFC6416 LATM-based AAC.
2. Extend AAC parser to, in addition to ADTS, handle LOAS encapsulation. (priority)
3. Consider refactoring the components to be more general 'MPEG-4 to RTP', since a dominant part of the RFC already do not differentiate AAC from general MPEG-4 audio streams.

Additional notes
4. Perhaps make the semantics in membrane_aac_format more consistent, right now the terms of AAC 'profiles' and 'object types' are confused, should refactor according to https://en.wikipedia.org/wiki/MPEG-4_Part_3

**Comment by kidq330** [comment]
After yesterday's SU the scope of this task was narrowed down to finishing the RFC3640 implementations. Work on the remaining issues will continue separately.
