### ISSUE TITLE
[Generator] BlankVideoGenerator causes pipeline to stuck on duration == 0

### ISSUE THREAD

**Issue by DominikWolek** [membraneframework/membrane_core#729]
Creating pipeline with 
```elixir
%BlankVideoGenerator{
  caps: %Membrane.Caps.Video.Raw{
      aligned: true,
      format: :I420,
      framerate: {4, 1},
      height: 360,
      width: 480
  },
  duration: 0
}
```
and `CutAndMerge` bin causes pipeline to stuck

**Comment by varsill** [comment]
I suspect that it might have been caused by the fact, that `end_of_stream` was not sent when `start_of_stream` hadn't been sent. 
I couldn't reproduce this one on the newest membrane_core, where we have changed the `end_of_stream` behaviour in https://github.com/membraneframework/membrane_core/pull/577
