### ISSUE TITLE
Support Enhanced RTMP in membrane_rtmp_plugin

### ISSUE THREAD

**Issue by andr-ec** [membraneframework/membrane_core#881]
This probably implies support for AV1 and HEVC.

It looks like someone already has an implementation of HEVC for membrane: https://github.com/gBillal/membrane_h265_ffmpeg_plugin

**Comment by mat-hek** [comment]
It's not in the roadmap yet, but when (if?) the adoption of Enhanced RTMP grows, we'll definitely give it a close look. H265 is indeed supported thanks to the someone, namely Billal ;) AV1 is not supported yet but it's on our roadmap.

For now, personally, this is how enhanced RTMP looks like to me 😄 

![image](https://github.com/user-attachments/assets/c88a14c6-d9ec-4189-a889-f0807e9664e6)

Simplicity is the best part of RTMP, and now instead of using something actually better (like SRT) they add more stuff to RTMP which doesn't quite fit ¯\\_(ツ)\_/¯ But I suppose there are some good reasons for it, let's see how the adoption goes.

**Comment by mat-hek** [comment]
It's not planned for now, so I moved that into discussions and answered there: https://github.com/orgs/membraneframework/discussions/882
